// Random values autogenerated by Mathematica
em_tensor.rho = -2.2942688762852868;
em_tensor.Si[0] = 86.77904725240842;
em_tensor.Si[1] = 62.95522653661101;
em_tensor.Si[2] = 103.81214597441794;
em_tensor.Sij[0][0] = 39096.59903541379;
em_tensor.Sij[0][1] = -21163.4707982371;
em_tensor.Sij[0][2] = 4173.05645441872;
em_tensor.Sij[1][0] = -21163.4707982371;
em_tensor.Sij[1][1] = -16623.958778730444;
em_tensor.Sij[1][2] = -38945.46859166979;
em_tensor.Sij[2][0] = 4173.05645441872;
em_tensor.Sij[2][1] = -38945.4685916698;
em_tensor.Sij[2][2] = -17102.738748707477;
em_tensor.S = -2.2679250098390185;


