// Random values autogenerated by Mathematica
em_tensor.rho = 0.3006454290697622;
em_tensor.Si[0] = 10.419346851264208;
em_tensor.Si[1] = -1.7073893159061981;
em_tensor.Si[2] = -7.7804742038645145;
em_tensor.Sij[0][0] = -414.75278901367346;
em_tensor.Sij[0][1] = 908.4012719743292;
em_tensor.Sij[0][2] = 1735.5568565050046;
em_tensor.Sij[1][0] = 908.4012719743291;
em_tensor.Sij[1][1] = 534.9894412820227;
em_tensor.Sij[1][2] = 398.19407600963495;
em_tensor.Sij[2][0] = 1735.5568565050046;
em_tensor.Sij[2][1] = 398.1940760096346;
em_tensor.Sij[2][2] = -195.6709254478815;
em_tensor.S = 0.30065580510634504;


