// Random values autogenerated by Mathematica
em_tensor.rho = 0.2633559514543329;
em_tensor.Si[0] = 1.7117392148691124;
em_tensor.Si[1] = -2.499859314317746;
em_tensor.Si[2] = -6.017991224889329;
em_tensor.Sij[0][0] = -864.9431835214141;
em_tensor.Sij[0][1] = 28.44562385147127;
em_tensor.Sij[0][2] = 1444.9906855919276;
em_tensor.Sij[1][0] = 28.445623851469662;
em_tensor.Sij[1][1] = 725.1826469077565;
em_tensor.Sij[1][2] = -3186.3735514807595;
em_tensor.Sij[2][0] = 1444.990685591927;
em_tensor.Sij[2][1] = -3186.3735514807586;
em_tensor.Sij[2][2] = 120.25227310068429;
em_tensor.S = 0.2830114019747043;


