// Random values autogenerated by Mathematica
em_tensor.rho = -1.228645064623472;
em_tensor.Si[0] = 0.23725670255799913;
em_tensor.Si[1] = -1.1877980377185873;
em_tensor.Si[2] = -0.454144274914482;
em_tensor.Sij[0][0] = 0.17340249784952466;
em_tensor.Sij[0][1] = -0.4922925295156276;
em_tensor.Sij[0][2] = 0.20878032667988494;
em_tensor.Sij[1][0] = -0.49229252951562724;
em_tensor.Sij[1][1] = 0.23271144155255047;
em_tensor.Sij[1][2] = 0.4384879250297374;
em_tensor.Sij[2][0] = 0.20878032667991803;
em_tensor.Sij[2][1] = 0.43848792502973755;
em_tensor.Sij[2][2] = 0.09941561975029717;
em_tensor.S = 0.5852474180849742;


