// Random values autogenerated by Mathematica
em_tensor.rho = -0.08700629311106423;
em_tensor.Si[0] = 0.027178026248900894;
em_tensor.Si[1] = -0.04786457279514386;
em_tensor.Si[2] = 0.41356535217224233;
em_tensor.Sij[0][0] = 0.21404712257419797;
em_tensor.Sij[0][1] = 1.7513395878768667;
em_tensor.Sij[0][2] = -0.026759703889427628;
em_tensor.Sij[1][0] = 1.7513395878768436;
em_tensor.Sij[1][1] = 2.8283650264126003;
em_tensor.Sij[1][2] = -1.611156675950483;
em_tensor.Sij[2][0] = -0.026759703889427645;
em_tensor.Sij[2][1] = -1.611156675950483;
em_tensor.Sij[2][2] = 3.650546137872634;
em_tensor.S = 6.819386370324684;


